on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: "Build & Release"

jobs:
  build-android:
    name: Build Android
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.0
          channel: stable

      - run: flutter pub get

      - name: Build Android Release APK
        run: |
          flutter build apk --release
          flutter build apk --release --split-per-abi

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/apk/release/*.apk

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.0
          channel: stable

      - run: flutter pub get

      - name: Build iOS Release IPA
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: Upload iOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/iphoneos/app.ipa

  build-web:
    name: Build Web
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.0
          channel: stable

      - run: flutter pub get

      - name: Build Web Release
        run: |
          flutter build web --release --base-href "/"
          cd build/web
          zip -r web.zip .

      - name: Upload Web Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-zip
          path: build/web/web.zip

  release:
    name: Push to Releases
    runs-on: macos-latest
    needs: [build-android, build-ios, build-web]
    steps:
      - name: Download Android Artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/apk/release/

      - name: Download iOS Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/iphoneos/

      - name: Download Web Artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-zip
          path: build/web/

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*.apk
            build/ios/iphoneos/app.ipa
            build/web/web.zip
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
